version: '3.8'

services:
  frontend:
    image: algofluent-frontend
    build:
      context: ./frontend
    ports:
      - "5000:5000"
  backend:
    image: algofluent-backend
    build:
      context: ./backend
    ports:
      - "4000:4000"
